### PR TITLE
fix Test-BISFService - parameter cannot be found

### PR DESCRIPTION
**Pull request by Siebrandf**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

Currently SCCM agent (ccmexec service) optimization is not run due to validation error. "Test-BISFService : A parameter cannot be found that matches parameter name 'eq'." Copied the if statement logic as used for SCOM

This PR fixes/implements the following **bugs/features**

* [x] Bug 1
* [ ] Bug 2
* [ ] Feature 1
* [ ] Feature 2
* [ ] Breaking changes

Explain the **motivation** for making this change. What existing problem does the pull request solve?

Does the code pass AppVeyor?
* [x] Yes

**Closing issues**

Fixes #

### CODE REVIEW

**Comment by Siebrandf** [comment]
Do you need any more info?

**Comment by matthias-schlimm** [comment]
No, thanks .. saw your PR . 


Am 05.12.2019 um 12:10 schrieb Siebrand Feenstra <notifications@github.com>:

**Review by matthias-schlimm — APPROVED** [review]
fix Test-BISFService - parameter cannot be found

**Review by matthias-schlimm — APPROVED** [review]
Edjust for compositing engine change

**Review by matthias-schlimm — APPROVED** [review]
fix Test-BISFService - parameter cannot be found

**Comment by matthias-schlimm** [comment]
manully merged into origin file

**Pull request closed without merging**
