### PR TITLE
Adjust to CAL 1911 compositing method change

### PR DESCRIPTION
**Pull request by Siebrandf**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

According to issue #150, this change detects if there's a 'CitrixCE' folder when Citrix App layering functionality is detected. If the 'CitrixCE' folder is detected the 1911 new compositing method is used which requires the bootorder to be changed which is retrieved from the bootid file under the 'CitrixCE' folder. If that is done, we replace the postcommand when LIC_BISF_CLI_SB is set to Yes

This PR fixes/implements the following **bugs/features**

* [ ] Bug 1
* [ ] Bug 2
* [x] Feature 1
* [ ] Feature 2
* [ ] Breaking changes

Explain the **motivation** for making this change. What existing problem does the pull request solve?

Does the code pass AppVeyor?
* [x] Yes

**Closing issues**

Fixes #

### CODE REVIEW

**Comment by Siebrandf** [comment]
Thanks in advance!

**Review by matthias-schlimm — APPROVED** [review]
Edjust for compositing engine change in AppLayering 1911 an higher

**Comment by matthias-schlimm** [comment]
Merge PR into branch -> Edjust for compositing engine change in AppLayering 1911 an higher

**Comment by matthias-schlimm** [comment]
merged into branch

**Pull request merged**
